In [27]:
import pandas as pd

df = pd.read_csv('/Users/johncabrahams/Desktop/Projects/Operation Algo/operation_dart_monkey/buy_data.csv')
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df

profits_losses asset  buy_index  time_held  buy_price  \
0             0.000  GHRS          0         57      0.000   
1             2.770  GHRS         57          3     23.220   
2            -1.470  GHRS         60          3     20.450   
3             1.815  GHRS         63         10     21.920   
4             2.915  GHRS         73          8     20.105   
..              ...   ...        ...        ...        ...   
951           0.220  MCFT        960          6     21.350   
952          -0.680  MCFT        966          4     21.130   
953          -0.190  MCFT        970          6     21.810   
954          -0.490  MCFT        976          4     22.000   
955           0.560  MCFT        980          8     22.490   

                      buy_date  
0    2021-06-25 04:00:00+00:00  
1    2021-09-16 04:00:00+00:00  
2    2021-09-21 04:00:00+00:00  
3    2021-09-24 04:00:00+00:00  
4    2021-10-08 04:00:00+00:00  
..                         ...  
951  2023-09-14 04:00:00+00:00  
952  2023-09-22 04:00:00+00:00  
953  2023-09-28 04:00:00+00:00  
954  2023-10-06 04:00:00+00:00  
955  2023-10-12 04:00:00+00:00  

[956 rows x 6 columns]

In [28]:
df_dummies = pd.get_dummies(df, columns=['asset'])

In [29]:
df.columns

Index(['profits_losses', 'asset', 'buy_index', 'time_held', 'buy_price',
       'buy_date'],
      dtype='object')

In [25]:
df_dummies

asset_list_of_pl = [df_dummies['profits_losses'].where(df_dummies['asset_BPOPM'] == True), df_dummies['profits_losses'].where(df_dummies['asset_TWIO'] == True)]

asset_list_of_pl[0].dropna(inplace=True)
asset_list_of_pl[1].dropna(inplace=True)

asset_list_of_pl = [sum(asset_list_of_pl[0]),sum(asset_list_of_pl[1])]




In [26]:
from scipy.stats import chi2_contingency
data = asset_list_of_pl
stat, p, dof, expected = chi2_contingency(data)
 
# interpret p-value
alpha = 0.05
print("p value is " + str(p))
if p <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (H0 holds true)')

p value is 1.0
Independent (H0 holds true)


In [34]:
X = df[['buy_index', 'time_held', 'buy_price']].values

y = df['profits_losses'].values

In [37]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')


Mean Squared Error: 42.92795592525971
R^2 Score: -0.002681131555790639
Model coefficients:
[ 0. 57.  0.]: 0.0005941756983954528
[57.    3.   23.22]: 0.009535363858243462
[60.    3.   20.45]: 0.003923250872266269
Intercept: -0.45399164257947355
